export class CountryTreeData {
    public static create() : any[] {
        let data: any[] = [];
        data.push({ Parent: null, Name: "Asia", Pop: NaN });
        data.push({ Parent: null, Name: "Middle East", Pop: NaN });
        data.push({ Parent: null, Name: "Europe", Pop: NaN });
        data.push({ Parent: null, Name: "North America", Pop: NaN });
        data.push({ Parent: null, Name: "Central America", Pop: NaN });
        data.push({ Parent: null, Name: "South America", Pop: NaN });
        data.push({ Parent: null, Name: "Africa", Pop: NaN });
        data.push({ Parent: null, Name: "Oceania", Pop: NaN });
        // creating children of tree data
        data.push({ Parent: "Africa", Name: "Angola", Pop: 19618432 });
        data.push({ Parent: "Africa", Name: "Benin", Pop: 9099922 });
        data.push({ Parent: "Africa", Name: "Botswana", Pop: 2030738 });
        data.push({ Parent: "Africa", Name: "Burkina Faso", Pop: 16967845 });
        data.push({ Parent: "Africa", Name: "Burundi", Pop: 8575172 });
        data.push({ Parent: "Africa", Name: "Cameroon", Pop: 20030362 });
        data.push({ Parent: "Africa", Name: "Cape Verde", Pop: 500585 });
        data.push({ Parent: "Africa", Name: "Central African Republic", Pop: 4486837 });
        data.push({ Parent: "Africa", Name: "Chad", Pop: 11525496 });
        data.push({ Parent: "Africa", Name: "Comoros", Pop: 753943 });
        data.push({ Parent: "Africa", Name: "Cote Ivoire", Pop: 20152894 });
        data.push({ Parent: "Africa", Name: "Djibouti", Pop: 905564 });
        data.push({ Parent: "Africa", Name: "Equatorial Guinea", Pop: 720213 });
        data.push({ Parent: "Africa", Name: "Eritrea", Pop: 5415280 });
        data.push({ Parent: "Africa", Name: "Ethiopia", Pop: 84734262 });
        data.push({ Parent: "Africa", Name: "Gabon", Pop: 1534262 });
        data.push({ Parent: "Africa", Name: "Gambia", Pop: 1776103 });
        data.push({ Parent: "Africa", Name: "Ghana", Pop: 24965816 });
        data.push({ Parent: "Africa", Name: "Guinea", Pop: 10221808 });
        data.push({ Parent: "Africa", Name: "Guinea-Bissau", Pop: 1547061 });
        data.push({ Parent: "Africa", Name: "Kenya", Pop: 41609728 });
        data.push({ Parent: "Africa", Name: "Lesotho", Pop: 2193843 });
        data.push({ Parent: "Africa", Name: "Liberia", Pop: 4128572 });
        data.push({ Parent: "Africa", Name: "Madagascar", Pop: 21315135 });
        data.push({ Parent: "Africa", Name: "Malawi", Pop: 15380888 });
        data.push({ Parent: "Africa", Name: "Mali", Pop: 15839538 });
        data.push({ Parent: "Africa", Name: "Mauritania", Pop: 3541540 });
        data.push({ Parent: "Africa", Name: "Mauritius", Pop: 1286051 });
        data.push({ Parent: "Africa", Name: "Mozambique", Pop: 23929708 });
        data.push({ Parent: "Africa", Name: "Namibia", Pop: 2324004 });
        data.push({ Parent: "Africa", Name: "Niger", Pop: 16068994 });
        data.push({ Parent: "Africa", Name: "Nigeria", Pop: 162470737 });
        data.push({ Parent: "Africa", Name: "Rwanda", Pop: 10942950 });
        data.push({ Parent: "Africa", Name: "Sao Tome and Principe", Pop: 168526 });
        data.push({ Parent: "Africa", Name: "Senegal", Pop: 12767556 });
        data.push({ Parent: "Africa", Name: "Seychelles", Pop: 86000 });
        data.push({ Parent: "Africa", Name: "Sierra Leone", Pop: 5997486 });
        data.push({ Parent: "Africa", Name: "South Africa", Pop: 50586757 });
        data.push({ Parent: "Africa", Name: "South Sudan", Pop: 10314021 });
        data.push({ Parent: "Africa", Name: "Sudan", Pop: 34318385 });
        data.push({ Parent: "Africa", Name: "Swaziland", Pop: 1067773 });
        data.push({ Parent: "Africa", Name: "Tanzania", Pop: 46218486 });
        data.push({ Parent: "Africa", Name: "Togo", Pop: 6154813 });
        data.push({ Parent: "Africa", Name: "Uganda", Pop: 34509205 });
        data.push({ Parent: "Africa", Name: "Zambia", Pop: 13474959 });
        data.push({ Parent: "Africa", Name: "Zimbabwe", Pop: 12754378 });
        data.push({ Parent: "Africa", Name: "Congo", Pop: 4139748 });
        data.push({ Parent: "Africa", Name: "Congo, Dem. Rep.", Pop: 67757577 });
        data.push({ Parent: "Asia", Name: "Bangladesh", Pop: 150493658 });
        data.push({ Parent: "Asia", Name: "Bhutan", Pop: 738267 });
        data.push({ Parent: "Asia", Name: "Brunei", Pop: 405938 });
        data.push({ Parent: "Asia", Name: "Cambodia", Pop: 14305183 });
        data.push({ Parent: "Asia", Name: "China", Pop: 1344130000 });
        data.push({ Parent: "Asia", Name: "India", Pop: 1241491960 });
        data.push({ Parent: "Asia", Name: "Indonesia", Pop: 242325638 });
        data.push({ Parent: "Asia", Name: "Japan", Pop: 127817277 });
        data.push({ Parent: "Asia", Name: "Kazakhstan", Pop: 16558676 });
        data.push({ Parent: "Asia", Name: "Kyrgyz Republic", Pop: 5514600 });
        data.push({ Parent: "Asia", Name: "Noth Korea", Pop: 24451285 });
        data.push({ Parent: "Asia", Name: "South Korea", Pop: 49779000 });
        data.push({ Parent: "Asia", Name: "Macao", Pop: 555731 });
        data.push({ Parent: "Asia", Name: "Hong Kong", Pop: 7071600 });
        data.push({ Parent: "Asia", Name: "Lao PDR", Pop: 6288037 });
        data.push({ Parent: "Asia", Name: "Malaysia", Pop: 28859154 });
        data.push({ Parent: "Asia", Name: "Maldives", Pop: 320081 });
        data.push({ Parent: "Asia", Name: "Mongolia", Pop: 2800114 });
        data.push({ Parent: "Asia", Name: "Myanmar", Pop: 48336763 });
        data.push({ Parent: "Asia", Name: "Nepal", Pop: 30485798 });
        data.push({ Parent: "Asia", Name: "Philippines", Pop: 94852030 });
        data.push({ Parent: "Asia", Name: "Singapore", Pop: 5183700 });
        data.push({ Parent: "Asia", Name: "Sri Lanka", Pop: 20869000 });
        data.push({ Parent: "Asia", Name: "Tajikistan", Pop: 6976958 });
        data.push({ Parent: "Asia", Name: "Thailand", Pop: 69518555 });
        data.push({ Parent: "Asia", Name: "Turkmenistan", Pop: 5105301 });
        data.push({ Parent: "Asia", Name: "Uzbekistan", Pop: 29341200 });
        data.push({ Parent: "Asia", Name: "Vietnam", Pop: 87840000 });
        data.push({ Parent: "Central America", Name: "Antigua and Barbuda", Pop: 89612 });
        data.push({ Parent: "Central America", Name: "Aruba", Pop: 108141 });
        data.push({ Parent: "Central America", Name: "Bahamas", Pop: 347176 });
        data.push({ Parent: "Central America", Name: "Barbados", Pop: 273925 });
        data.push({ Parent: "Central America", Name: "Belize", Pop: 356600 });
        data.push({ Parent: "Central America", Name: "Bermuda", Pop: 64700 });
        data.push({ Parent: "Central America", Name: "Cayman Islands", Pop: 56729 });
        data.push({ Parent: "Central America", Name: "Costa Rica", Pop: 4726575 });
        data.push({ Parent: "Central America", Name: "Cuba", Pop: 11253665 });
        data.push({ Parent: "Central America", Name: "Curacao", Pop: 145619 });
        data.push({ Parent: "Central America", Name: "Dominica", Pop: 67675 });
        data.push({ Parent: "Central America", Name: "Dominican Republic", Pop: 10056181 });
        data.push({ Parent: "Central America", Name: "Faeroe Islands", Pop: 48863 });
        data.push({ Parent: "Central America", Name: "Grenada", Pop: 104890 });
        data.push({ Parent: "Central America", Name: "Guam", Pop: 182111 });
        data.push({ Parent: "Central America", Name: "Guatemala", Pop: 14757316 });
        data.push({ Parent: "Central America", Name: "Haiti", Pop: 10123787 });
        data.push({ Parent: "Central America", Name: "Honduras", Pop: 7754687 });
        data.push({ Parent: "Central America", Name: "Jamaica", Pop: 2706500 });
        data.push({ Parent: "Central America", Name: "Nicaragua", Pop: 5869859 });
        data.push({ Parent: "Central America", Name: "Northern Mariana Islands", Pop: 61174 });
        data.push({ Parent: "Central America", Name: "Panama", Pop: 3571185 });
        data.push({ Parent: "Central America", Name: "St. Kitts and Nevis", Pop: 53051 });
        data.push({ Parent: "Central America", Name: "St. Lucia", Pop: 176000 });
        data.push({ Parent: "Central America", Name: "St. Vincent and the Grenadines", Pop: 109365 });
        data.push({ Parent: "Central America", Name: "Trinidad and Tobago", Pop: 1346350 });
        data.push({ Parent: "Central America", Name: "Turks and Caicos Islands", Pop: 39184 });
        data.push({ Parent: "Central America", Name: "Virgin Islands (U.S.)", Pop: 109666 });
        data.push({ Parent: "Central America", Name: "El Salvador", Pop: 6227491 });
        data.push({ Parent: "Central America", Name: "Puerto Rico", Pop: 3706690 });
        data.push({ Parent: "Europe", Name: "Albania", Pop: 3215988 });
        data.push({ Parent: "Europe", Name: "Andorra", Pop: 86165 });
        data.push({ Parent: "Europe", Name: "Armenia", Pop: 3100236 });
        data.push({ Parent: "Europe", Name: "Austria", Pop: 8423635 });
        data.push({ Parent: "Europe", Name: "Belarus", Pop: 9473000 });
        data.push({ Parent: "Europe", Name: "Belgium", Pop: 11020952 });
        data.push({ Parent: "Europe", Name: "Bosnia and Herzegovina", Pop: 3752228 });
        data.push({ Parent: "Europe", Name: "Bulgaria", Pop: 7348328 });
        data.push({ Parent: "Europe", Name: "Channel Islands", Pop: 153876 });
        data.push({ Parent: "Europe", Name: "Croatia", Pop: 4403000 });
        data.push({ Parent: "Europe", Name: "Cyprus", Pop: 1116564 });
        data.push({ Parent: "Europe", Name: "Czechia", Pop: 10496088 });
        data.push({ Parent: "Europe", Name: "Denmark", Pop: 5570572 });
        data.push({ Parent: "Europe", Name: "Estonia", Pop: 1339928 });
        data.push({ Parent: "Europe", Name: "Finland", Pop: 5388272 });
        data.push({ Parent: "Europe", Name: "France", Pop: 65433714 });
        data.push({ Parent: "Europe", Name: "Georgia", Pop: 4486000 });
        data.push({ Parent: "Europe", Name: "Germany", Pop: 81797673 });
        data.push({ Parent: "Europe", Name: "Greece", Pop: 11300410 });
        data.push({ Parent: "Europe", Name: "Hungary", Pop: 9971727 });
        data.push({ Parent: "Europe", Name: "Iceland", Pop: 319014 });
        data.push({ Parent: "Europe", Name: "Ireland", Pop: 4576317 });
        data.push({ Parent: "Europe", Name: "Isle of Man", Pop: 83327 });
        data.push({ Parent: "Europe", Name: "Italy", Pop: 60723603 });
        data.push({ Parent: "Europe", Name: "Kosovo", Pop: 1802765 });
        data.push({ Parent: "Europe", Name: "Latvia", Pop: 2058184 });
        data.push({ Parent: "Europe", Name: "Liechtenstein", Pop: 36304 });
        data.push({ Parent: "Europe", Name: "Lithuania", Pop: 3030173 });
        data.push({ Parent: "Europe", Name: "Luxembourg", Pop: 518252 });
        data.push({ Parent: "Europe", Name: "Malta", Pop: 415654 });
        data.push({ Parent: "Europe", Name: "Moldova", Pop: 3559000 });
        data.push({ Parent: "Europe", Name: "Monaco", Pop: 35427 });
        data.push({ Parent: "Europe", Name: "Montenegro", Pop: 632261 });
        data.push({ Parent: "Europe", Name: "Netherlands", Pop: 16693074 });
        data.push({ Parent: "Europe", Name: "Norway", Pop: 4953088 });
        data.push({ Parent: "Europe", Name: "Poland", Pop: 38534157 });
        data.push({ Parent: "Europe", Name: "Portugal", Pop: 10556999 });
        data.push({ Parent: "Europe", Name: "Romania", Pop: 21384832 });
        data.push({ Parent: "Europe", Name: "Russian", Pop: 142960000 });
        data.push({ Parent: "Europe", Name: "San Marino", Pop: 31735 });
        data.push({ Parent: "Europe", Name: "Serbia", Pop: 7258745 });
        data.push({ Parent: "Europe", Name: "Sint Maarten", Pop: 36609 });
        data.push({ Parent: "Europe", Name: "Slovak Republic", Pop: 5398384 });
        data.push({ Parent: "Europe", Name: "Slovenia", Pop: 2052843 });
        data.push({ Parent: "Europe", Name: "Spain", Pop: 46174601 });
        data.push({ Parent: "Europe", Name: "St. Martin (French part)", Pop: 30615 });
        data.push({ Parent: "Europe", Name: "Sweden", Pop: 9449213 });
        data.push({ Parent: "Europe", Name: "Switzerland", Pop: 7912398 });
        data.push({ Parent: "Europe", Name: "Ukraine", Pop: 45706100 });
        data.push({ Parent: "Europe", Name: "United Kingdom", Pop: 62744081 });
        data.push({ Parent: "Europe", Name: "Macedonia, FYR", Pop: 2063893 });
        data.push({ Parent: "Middle East", Name: "Afghanistan", Pop: 35320445 });
        data.push({ Parent: "Middle East", Name: "Algeria", Pop: 35980193 });
        data.push({ Parent: "Middle East", Name: "Azerbaijan", Pop: 9173082 });
        data.push({ Parent: "Middle East", Name: "Bahrain", Pop: 1323535 });
        data.push({ Parent: "Middle East", Name: "Iraq", Pop: 32961959 });
        data.push({ Parent: "Middle East", Name: "Israel", Pop: 7765900 });
        data.push({ Parent: "Middle East", Name: "Jordan", Pop: 6181000 });
        data.push({ Parent: "Middle East", Name: "Kuwait", Pop: 2818042 });
        data.push({ Parent: "Middle East", Name: "Lebanon", Pop: 4259405 });
        data.push({ Parent: "Middle East", Name: "Libya", Pop: 6422772 });
        data.push({ Parent: "Middle East", Name: "Morocco", Pop: 32272974 });
        data.push({ Parent: "Middle East", Name: "Oman", Pop: 2846145 });
        data.push({ Parent: "Middle East", Name: "Pakistan", Pop: 176745364 });
        data.push({ Parent: "Middle East", Name: "Qatar", Pop: 1870041 });
        data.push({ Parent: "Middle East", Name: "Saudi Arabia", Pop: 28082541 });
        data.push({ Parent: "Middle East", Name: "Somalia", Pop: 9556873 });
        data.push({ Parent: "Middle East", Name: "Syrian Arab Republic", Pop: 20820311 });
        data.push({ Parent: "Middle East", Name: "Tunisia", Pop: 10673800 });
        data.push({ Parent: "Middle East", Name: "Turkey", Pop: 73639596 });
        data.push({ Parent: "Middle East", Name: "United Arab Emirates", Pop: 7890924 });
        data.push({ Parent: "Middle East", Name: "West Bank and Gaza", Pop: 3927051 });
        data.push({ Parent: "Middle East", Name: "Yemen", Pop: 24799880 });
        data.push({ Parent: "Middle East", Name: "Iran", Pop: 74798599 });
        data.push({ Parent: "Middle East", Name: "Egypt.", Pop: 82536770 });
        data.push({ Parent: "North America", Name: "Canada", Pop: 34483975 });
        data.push({ Parent: "North America", Name: "Greenland", Pop: 56840 });
        data.push({ Parent: "North America", Name: "Mexico", Pop: 114793341 });
        data.push({ Parent: "North America", Name: "United States", Pop: 311591917 });
        data.push({ Parent: "Oceania", Name: "American Samoa", Pop: 69543 });
        data.push({ Parent: "Oceania", Name: "Australia", Pop: 22323900 });
        data.push({ Parent: "Oceania", Name: "Fiji", Pop: 868406 });
        data.push({ Parent: "Oceania", Name: "French Polynesia", Pop: 273777 });
        data.push({ Parent: "Oceania", Name: "Kiribati", Pop: 101093 });
        data.push({ Parent: "Oceania", Name: "Marshall Islands", Pop: 54816 });
        data.push({ Parent: "Oceania", Name: "New Caledonia", Pop: 254024 });
        data.push({ Parent: "Oceania", Name: "New Zealand", Pop: 4405200 });
        data.push({ Parent: "Oceania", Name: "Palau", Pop: 20609 });
        data.push({ Parent: "Oceania", Name: "Papua New Guinea", Pop: 7013829 });
        data.push({ Parent: "Oceania", Name: "Samoa", Pop: 183874 });
        data.push({ Parent: "Oceania", Name: "Timor-Leste", Pop: 1175880 });
        data.push({ Parent: "Oceania", Name: "Tonga", Pop: 104509 });
        data.push({ Parent: "Oceania", Name: "Tuvalu", Pop: 9847 });
        data.push({ Parent: "Oceania", Name: "Vanuatu", Pop: 245619 });
        data.push({ Parent: "Oceania", Name: "Micronesia", Pop: 111542 });
        data.push({ Parent: "Oceania", Name: "Solomon Islands", Pop: 552267 });
        data.push({ Parent: "South America", Name: "Argentina", Pop: 40764561 });
        data.push({ Parent: "South America", Name: "Bolivia", Pop: 10088108 });
        data.push({ Parent: "South America", Name: "Brazil", Pop: 196655014 });
        data.push({ Parent: "South America", Name: "Chile", Pop: 17269525 });
        data.push({ Parent: "South America", Name: "Colombia", Pop: 46927125 });
        data.push({ Parent: "South America", Name: "Ecuador", Pop: 14666055 });
        data.push({ Parent: "South America", Name: "Guyana", Pop: 756040 });
        data.push({ Parent: "South America", Name: "Paraguay", Pop: 6568290 });
        data.push({ Parent: "South America", Name: "Peru", Pop: 29399817 });
        data.push({ Parent: "South America", Name: "Suriname", Pop: 529419 });
        data.push({ Parent: "South America", Name: "Uruguay", Pop: 3368595 });
        data.push({ Parent: "South America", Name: "Venezuela", Pop: 29278000 });
        return data;
    }
}