# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "vnext" ]
  pull_request:
    branches: [ "vnext" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./browser # The working directory path

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: browser/package-lock.json
    
    # THIS WILL BE REMOVED WHEN WE SWITCH BACK TO PUBLIC PACKAGES
    # - name: Setup Registry
    #   run: |
    #     echo "@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/" >> ~/.npmrc
    #     echo "//packages.infragistics.com/npm/js-licensed/:_auth=${{ secrets.PROGET_TOKEN }}" >> ~/.npmrc
    #     echo "//packages.infragistics.com/npm/js-licensed/:always-auth=true" >> ~/.npmrc

    - name: npm ci
      run: npm ci
    - name: Build
      run: npm run build
