trigger:
  branches:
    include:
    - vnext
    - master

pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildSamples
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.18.1'

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)/browser/'
          customCommand: 'config -L project set @infragistics:registry=https://packages.infragistics.com/npm/js-licensed/'

      - task: npmAuthenticate@0
        inputs:
          workingFile: '$(Build.SourcesDirectory)/browser/.npmrc'
          customEndpoint: 'public proget'

      - task: CmdLine@2
        inputs:
          script: 'type .\.npmrc'
          workingDirectory: '$(Build.SourcesDirectory)\browser'
          failOnStderr: true

      - task: Npm@1
        displayName: 'npm ci'
        inputs:
          command: custom
          workingDir: '$(Build.SourcesDirectory)\browser'
          verbose: ${{ parameters.isVerbose }}
          #customCommand: ci
          customCommand: install
      - task: Npm@1
        displayName: 'npm uninstall igniteui-dockmanager (trial)'
        inputs:
          command: custom
          workingDir: '$(Build.SourcesDirectory)\browser'
          verbose: ${{ parameters.isVerbose }}
          customCommand: 'uninstall igniteui-dockmanager'

      - task: CmdLine@2
        inputs:
          script: 'choco install jq -y'
          failOnStderr: true

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)\browser
            npm install igniteui-dockmanager@npm:@infragistics/igniteui-dockmanager@$($(jq '.dependencies.\"igniteui-dockmanager\"' .\package.json).Trim('"'))


      - task: PublishPipelineArtifact@1
        displayName: 'Publish pipeline artifacts'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'ReactSamplesBrowser'